# Generated by Django 4.2.16 on 2025-01-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(default=1, upload_to='service_icons/'),
            preserve_default=False,
        ),
    ]
